---
- name: "Add Docker’s official GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when:
    - ansible_architecture == "x86_64"

- name: Install docker engine
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - "aufs-tools=1:4.9+20170918-1ubuntu1"
      - "cgroupfs-mount=1.4"
      - "libltdl7=2.4.6-2"
      - "pigz=2.4-1"
      - "docker-ce=5:19.03.2~3-0~ubuntu-bionic"
      - "docker-ce-cli=5:19.03.2~3-0~ubuntu-bionic"
      - "containerd.io=1.2.6-3"

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0777'
    owner: root
    group: root
  notify:
    - "Docker compose installed"